#############################################################################
# Makefile for building: P2PSystem
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  P2PSystem.pro
# Template: subdirs
# Command: /home/lht/Qt/5.2.1/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile P2PSystem.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /home/lht/Qt/5.2.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-PCPServer \
		sub-PCPClient \
		sub-libjingle \
		sub-libjingle_p2p \
		sub-libjingle_app


sub-PCPServer-qmake_all:  FORCE
	@test -d PCPServer/ || mkdir -p PCPServer/
	cd PCPServer/ && $(QMAKE) /home/lht/workspace/P2PSystem/PCPServer/PCPServer.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd PCPServer/ && $(MAKE) -f Makefile qmake_all
sub-PCPServer: FORCE
	@test -d PCPServer/ || mkdir -p PCPServer/
	cd PCPServer/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPServer/PCPServer.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-PCPServer-make_first: FORCE
	@test -d PCPServer/ || mkdir -p PCPServer/
	cd PCPServer/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPServer/PCPServer.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-PCPServer-all: FORCE
	@test -d PCPServer/ || mkdir -p PCPServer/
	cd PCPServer/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPServer/PCPServer.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-PCPServer-clean: FORCE
	@test -d PCPServer/ || mkdir -p PCPServer/
	cd PCPServer/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPServer/PCPServer.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-PCPServer-distclean: FORCE
	@test -d PCPServer/ || mkdir -p PCPServer/
	cd PCPServer/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPServer/PCPServer.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-PCPServer-install_subtargets: FORCE
	@test -d PCPServer/ || mkdir -p PCPServer/
	cd PCPServer/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPServer/PCPServer.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-PCPServer-uninstall_subtargets: FORCE
	@test -d PCPServer/ || mkdir -p PCPServer/
	cd PCPServer/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPServer/PCPServer.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-PCPClient-qmake_all:  FORCE
	@test -d PCPClient/ || mkdir -p PCPClient/
	cd PCPClient/ && $(QMAKE) /home/lht/workspace/P2PSystem/PCPClient/PCPClient.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd PCPClient/ && $(MAKE) -f Makefile qmake_all
sub-PCPClient: FORCE
	@test -d PCPClient/ || mkdir -p PCPClient/
	cd PCPClient/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPClient/PCPClient.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-PCPClient-make_first: FORCE
	@test -d PCPClient/ || mkdir -p PCPClient/
	cd PCPClient/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPClient/PCPClient.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-PCPClient-all: FORCE
	@test -d PCPClient/ || mkdir -p PCPClient/
	cd PCPClient/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPClient/PCPClient.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-PCPClient-clean: FORCE
	@test -d PCPClient/ || mkdir -p PCPClient/
	cd PCPClient/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPClient/PCPClient.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-PCPClient-distclean: FORCE
	@test -d PCPClient/ || mkdir -p PCPClient/
	cd PCPClient/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPClient/PCPClient.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-PCPClient-install_subtargets: FORCE
	@test -d PCPClient/ || mkdir -p PCPClient/
	cd PCPClient/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPClient/PCPClient.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-PCPClient-uninstall_subtargets: FORCE
	@test -d PCPClient/ || mkdir -p PCPClient/
	cd PCPClient/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPClient/PCPClient.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-libjingle-qmake_all:  FORCE
	@test -d libjingle/ || mkdir -p libjingle/
	cd libjingle/ && $(QMAKE) /home/lht/workspace/P2PSystem/libjingle/libjingle.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd libjingle/ && $(MAKE) -f Makefile qmake_all
sub-libjingle: FORCE
	@test -d libjingle/ || mkdir -p libjingle/
	cd libjingle/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle/libjingle.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-libjingle-make_first: FORCE
	@test -d libjingle/ || mkdir -p libjingle/
	cd libjingle/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle/libjingle.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-libjingle-all: FORCE
	@test -d libjingle/ || mkdir -p libjingle/
	cd libjingle/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle/libjingle.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-libjingle-clean: FORCE
	@test -d libjingle/ || mkdir -p libjingle/
	cd libjingle/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle/libjingle.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-libjingle-distclean: FORCE
	@test -d libjingle/ || mkdir -p libjingle/
	cd libjingle/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle/libjingle.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-libjingle-install_subtargets: FORCE
	@test -d libjingle/ || mkdir -p libjingle/
	cd libjingle/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle/libjingle.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-libjingle-uninstall_subtargets: FORCE
	@test -d libjingle/ || mkdir -p libjingle/
	cd libjingle/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle/libjingle.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-libjingle_p2p-qmake_all:  FORCE
	@test -d libjingle_p2p/ || mkdir -p libjingle_p2p/
	cd libjingle_p2p/ && $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_p2p/libjingle_p2p.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd libjingle_p2p/ && $(MAKE) -f Makefile qmake_all
sub-libjingle_p2p: FORCE
	@test -d libjingle_p2p/ || mkdir -p libjingle_p2p/
	cd libjingle_p2p/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_p2p/libjingle_p2p.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-libjingle_p2p-make_first: FORCE
	@test -d libjingle_p2p/ || mkdir -p libjingle_p2p/
	cd libjingle_p2p/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_p2p/libjingle_p2p.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-libjingle_p2p-all: FORCE
	@test -d libjingle_p2p/ || mkdir -p libjingle_p2p/
	cd libjingle_p2p/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_p2p/libjingle_p2p.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-libjingle_p2p-clean: FORCE
	@test -d libjingle_p2p/ || mkdir -p libjingle_p2p/
	cd libjingle_p2p/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_p2p/libjingle_p2p.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-libjingle_p2p-distclean: FORCE
	@test -d libjingle_p2p/ || mkdir -p libjingle_p2p/
	cd libjingle_p2p/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_p2p/libjingle_p2p.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-libjingle_p2p-install_subtargets: FORCE
	@test -d libjingle_p2p/ || mkdir -p libjingle_p2p/
	cd libjingle_p2p/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_p2p/libjingle_p2p.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-libjingle_p2p-uninstall_subtargets: FORCE
	@test -d libjingle_p2p/ || mkdir -p libjingle_p2p/
	cd libjingle_p2p/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_p2p/libjingle_p2p.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-libjingle_app-qmake_all:  FORCE
	@test -d libjingle_app/ || mkdir -p libjingle_app/
	cd libjingle_app/ && $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_app/libjingle_app.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd libjingle_app/ && $(MAKE) -f Makefile qmake_all
sub-libjingle_app: FORCE
	@test -d libjingle_app/ || mkdir -p libjingle_app/
	cd libjingle_app/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_app/libjingle_app.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-libjingle_app-make_first: FORCE
	@test -d libjingle_app/ || mkdir -p libjingle_app/
	cd libjingle_app/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_app/libjingle_app.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-libjingle_app-all: FORCE
	@test -d libjingle_app/ || mkdir -p libjingle_app/
	cd libjingle_app/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_app/libjingle_app.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-libjingle_app-clean: FORCE
	@test -d libjingle_app/ || mkdir -p libjingle_app/
	cd libjingle_app/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_app/libjingle_app.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-libjingle_app-distclean: FORCE
	@test -d libjingle_app/ || mkdir -p libjingle_app/
	cd libjingle_app/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_app/libjingle_app.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-libjingle_app-install_subtargets: FORCE
	@test -d libjingle_app/ || mkdir -p libjingle_app/
	cd libjingle_app/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_app/libjingle_app.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-libjingle_app-uninstall_subtargets: FORCE
	@test -d libjingle_app/ || mkdir -p libjingle_app/
	cd libjingle_app/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_app/libjingle_app.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: P2PSystem.pro ../../Qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/lex.prf \
		P2PSystem.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile P2PSystem.pro
../../Qt/5.2.1/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt/5.2.1/gcc_64/mkspecs/common/shell-unix.conf:
../../Qt/5.2.1/gcc_64/mkspecs/common/unix.conf:
../../Qt/5.2.1/gcc_64/mkspecs/common/linux.conf:
../../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt/5.2.1/gcc_64/mkspecs/common/g++-base.conf:
../../Qt/5.2.1/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt/5.2.1/gcc_64/mkspecs/qconfig.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.2.1/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt/5.2.1/gcc_64/mkspecs/features/qt_config.prf:
../../Qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt/5.2.1/gcc_64/mkspecs/features/spec_post.prf:
../../Qt/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.2.1/gcc_64/mkspecs/features/default_pre.prf:
../../Qt/5.2.1/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt/5.2.1/gcc_64/mkspecs/features/default_post.prf:
../../Qt/5.2.1/gcc_64/mkspecs/features/qml_debug.prf:
../../Qt/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf:
../../Qt/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../../Qt/5.2.1/gcc_64/mkspecs/features/warn_on.prf:
../../Qt/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.2.1/gcc_64/mkspecs/features/exceptions.prf:
../../Qt/5.2.1/gcc_64/mkspecs/features/yacc.prf:
../../Qt/5.2.1/gcc_64/mkspecs/features/lex.prf:
P2PSystem.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile P2PSystem.pro

qmake_all: sub-PCPServer-qmake_all sub-PCPClient-qmake_all sub-libjingle-qmake_all sub-libjingle_p2p-qmake_all sub-libjingle_app-qmake_all FORCE

make_first: sub-PCPServer-make_first sub-PCPClient-make_first sub-libjingle-make_first sub-libjingle_p2p-make_first sub-libjingle_app-make_first FORCE
all: sub-PCPServer-all sub-PCPClient-all sub-libjingle-all sub-libjingle_p2p-all sub-libjingle_app-all FORCE
clean: sub-PCPServer-clean sub-PCPClient-clean sub-libjingle-clean sub-libjingle_p2p-clean sub-libjingle_app-clean FORCE
distclean: sub-PCPServer-distclean sub-PCPClient-distclean sub-libjingle-distclean sub-libjingle_p2p-distclean sub-libjingle_app-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-PCPServer-install_subtargets sub-PCPClient-install_subtargets sub-libjingle-install_subtargets sub-libjingle_p2p-install_subtargets sub-libjingle_app-install_subtargets FORCE
uninstall_subtargets: sub-PCPServer-uninstall_subtargets sub-PCPClient-uninstall_subtargets sub-libjingle-uninstall_subtargets sub-libjingle_p2p-uninstall_subtargets sub-libjingle_app-uninstall_subtargets FORCE

sub-PCPServer-check:
	@test -d PCPServer/ || mkdir -p PCPServer/
	cd PCPServer/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPServer/PCPServer.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-PCPClient-check:
	@test -d PCPClient/ || mkdir -p PCPClient/
	cd PCPClient/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/PCPClient/PCPClient.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-libjingle-check:
	@test -d libjingle/ || mkdir -p libjingle/
	cd libjingle/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle/libjingle.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-libjingle_p2p-check:
	@test -d libjingle_p2p/ || mkdir -p libjingle_p2p/
	cd libjingle_p2p/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_p2p/libjingle_p2p.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-libjingle_app-check:
	@test -d libjingle_app/ || mkdir -p libjingle_app/
	cd libjingle_app/ && ( test -e Makefile || $(QMAKE) /home/lht/workspace/P2PSystem/libjingle_app/libjingle_app.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-PCPServer-check sub-PCPClient-check sub-libjingle-check sub-libjingle_p2p-check sub-libjingle_app-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

