#ifndef TESTSHARELIB_GLOBAL_H
#define TESTSHARELIB_GLOBAL_H

//#include <QtCore/qglobal.h>

//#if defined(TESTSHARELIB_LIBRARY)
//#  define TESTSHARELIBSHARED_EXPORT Q_DECL_EXPORT
//#else
//#  define TESTSHARELIBSHARED_EXPORT Q_DECL_IMPORT
//#endif

#endif // TESTSHARELIB_GLOBAL_H
