#ifndef KECAMERAPLUGIN_GLOBAL_H
#define KECAMERAPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KECAMERAPLUGIN_LIBRARY)
#  define KECAMERAPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define KECAMERAPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // KECAMERAPLUGIN_GLOBAL_H
