# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := libjingle_peerconnection_test_jar
### Rules for action "create_jar":
quiet_cmd__home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_test_jar_target_create_jar = ACTION _home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_test_jar_target_create_jar $@
cmd__home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_test_jar_target_create_jar = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd talk; mkdir -p $(builddir); build/build_jar.sh /usr/lib/jvm/java-1.7.0-openjdk-i386 "$(builddir)/libjingle_peerconnection_test.jar" "$(obj).$(TOOLSET)/libjingle_peerconnection_test_jar/geni" "app/webrtc/javatests/src:$(builddir)/libjingle_peerconnection.jar:../third_party/junit/junit-4.11.jar" app/webrtc/javatests/src/org/webrtc/PeerConnectionTest.java

$(builddir)/libjingle_peerconnection_test.jar: obj := $(abs_obj)
$(builddir)/libjingle_peerconnection_test.jar: builddir := $(abs_builddir)
$(builddir)/libjingle_peerconnection_test.jar: TOOLSET := $(TOOLSET)
$(builddir)/libjingle_peerconnection_test.jar: talk/build/build_jar.sh talk/app/webrtc/javatests/src/org/webrtc/PeerConnectionTest.java $(builddir)/libjingle_peerconnection.jar third_party/junit/junit-4.11.jar FORCE_DO_CMD
	$(call do_cmd,_home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_test_jar_target_create_jar)

all_deps += $(builddir)/libjingle_peerconnection_test.jar
action__home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_test_jar_target_create_jar_outputs := $(builddir)/libjingle_peerconnection_test.jar


### Rules for final target.
# Build our special outputs first.
$(obj).target/talk/libjingle_peerconnection_test_jar.stamp: | $(action__home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_test_jar_target_create_jar_outputs)

# Preserve order dependency of special output on deps.
$(action__home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_test_jar_target_create_jar_outputs): | $(obj).target/build/linux/ssl.stamp

$(obj).target/talk/libjingle_peerconnection_test_jar.stamp: TOOLSET := $(TOOLSET)
$(obj).target/talk/libjingle_peerconnection_test_jar.stamp: $(obj).target/build/linux/ssl.stamp FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/talk/libjingle_peerconnection_test_jar.stamp
# Add target alias
.PHONY: libjingle_peerconnection_test_jar
libjingle_peerconnection_test_jar: $(obj).target/talk/libjingle_peerconnection_test_jar.stamp

# Add target alias to "all" target.
.PHONY: all
all: libjingle_peerconnection_test_jar

