# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := libjingle_peerconnection_jar
### Rules for action "create_jar":
quiet_cmd__home_lht_webrtc_trunk_talk_libjingle_gyp_libjingle_peerconnection_jar_target_create_jar = ACTION _home_lht_webrtc_trunk_talk_libjingle_gyp_libjingle_peerconnection_jar_target_create_jar $@
cmd__home_lht_webrtc_trunk_talk_libjingle_gyp_libjingle_peerconnection_jar_target_create_jar = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd talk; mkdir -p $(builddir); bash -ec "mkdir -p $(obj).$(TOOLSET)/libjingle_peerconnection_jar/geni && { build/build_jar.sh /usr/lib/jvm/java-1.7.0-openjdk-i386 \"$(builddir)/libjingle_peerconnection.jar\"       $(obj).$(TOOLSET)/libjingle_peerconnection_jar/geni/build_jar.tmp       app/webrtc/java/src app/webrtc/java/src/org/webrtc/AudioSource.java app/webrtc/java/src/org/webrtc/AudioTrack.java app/webrtc/java/src/org/webrtc/DataChannel.java app/webrtc/java/src/org/webrtc/IceCandidate.java app/webrtc/java/src/org/webrtc/Logging.java app/webrtc/java/src/org/webrtc/MediaConstraints.java app/webrtc/java/src/org/webrtc/MediaSource.java app/webrtc/java/src/org/webrtc/MediaStream.java app/webrtc/java/src/org/webrtc/MediaStreamTrack.java app/webrtc/java/src/org/webrtc/PeerConnectionFactory.java app/webrtc/java/src/org/webrtc/PeerConnection.java app/webrtc/java/src/org/webrtc/SdpObserver.java app/webrtc/java/src/org/webrtc/StatsObserver.java app/webrtc/java/src/org/webrtc/StatsReport.java app/webrtc/java/src/org/webrtc/SessionDescription.java app/webrtc/java/src/org/webrtc/VideoCapturer.java app/webrtc/java/src/org/webrtc/VideoRenderer.java app/webrtc/java/src/org/webrtc/VideoSource.java app/webrtc/java/src/org/webrtc/VideoTrack.java       > $(obj).$(TOOLSET)/libjingle_peerconnection_jar/geni/build_jar.log 2>&1 ||   { cat $(obj).$(TOOLSET)/libjingle_peerconnection_jar/geni/build_jar.log ; exit 1; } }"

$(builddir)/libjingle_peerconnection.jar: obj := $(abs_obj)
$(builddir)/libjingle_peerconnection.jar: builddir := $(abs_builddir)
$(builddir)/libjingle_peerconnection.jar: TOOLSET := $(TOOLSET)
$(builddir)/libjingle_peerconnection.jar: talk/build/build_jar.sh talk/app/webrtc/java/src/org/webrtc/AudioSource.java talk/app/webrtc/java/src/org/webrtc/AudioTrack.java talk/app/webrtc/java/src/org/webrtc/DataChannel.java talk/app/webrtc/java/src/org/webrtc/IceCandidate.java talk/app/webrtc/java/src/org/webrtc/Logging.java talk/app/webrtc/java/src/org/webrtc/MediaConstraints.java talk/app/webrtc/java/src/org/webrtc/MediaSource.java talk/app/webrtc/java/src/org/webrtc/MediaStream.java talk/app/webrtc/java/src/org/webrtc/MediaStreamTrack.java talk/app/webrtc/java/src/org/webrtc/PeerConnectionFactory.java talk/app/webrtc/java/src/org/webrtc/PeerConnection.java talk/app/webrtc/java/src/org/webrtc/SdpObserver.java talk/app/webrtc/java/src/org/webrtc/StatsObserver.java talk/app/webrtc/java/src/org/webrtc/StatsReport.java talk/app/webrtc/java/src/org/webrtc/SessionDescription.java talk/app/webrtc/java/src/org/webrtc/VideoCapturer.java talk/app/webrtc/java/src/org/webrtc/VideoRenderer.java talk/app/webrtc/java/src/org/webrtc/VideoSource.java talk/app/webrtc/java/src/org/webrtc/VideoTrack.java FORCE_DO_CMD
	$(call do_cmd,_home_lht_webrtc_trunk_talk_libjingle_gyp_libjingle_peerconnection_jar_target_create_jar)

all_deps += $(builddir)/libjingle_peerconnection.jar
action__home_lht_webrtc_trunk_talk_libjingle_gyp_libjingle_peerconnection_jar_target_create_jar_outputs := $(builddir)/libjingle_peerconnection.jar


### Rules for final target.
# Build our special outputs first.
$(obj).target/talk/libjingle_peerconnection_jar.stamp: | $(action__home_lht_webrtc_trunk_talk_libjingle_gyp_libjingle_peerconnection_jar_target_create_jar_outputs)

# Preserve order dependency of special output on deps.
$(action__home_lht_webrtc_trunk_talk_libjingle_gyp_libjingle_peerconnection_jar_target_create_jar_outputs): | $(obj).target/build/linux/ssl.stamp $(builddir)/libjingle_peerconnection_so.so

$(obj).target/talk/libjingle_peerconnection_jar.stamp: TOOLSET := $(TOOLSET)
$(obj).target/talk/libjingle_peerconnection_jar.stamp: $(obj).target/build/linux/ssl.stamp $(builddir)/libjingle_peerconnection_so.so FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/talk/libjingle_peerconnection_jar.stamp
# Add target alias
.PHONY: libjingle_peerconnection_jar
libjingle_peerconnection_jar: $(obj).target/talk/libjingle_peerconnection_jar.stamp

# Add target alias to "all" target.
.PHONY: all
all: libjingle_peerconnection_jar

