# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := libjingle_peerconnection_java_unittest
### Rules for action "copy libjingle_peerconnection_java_unittest":
quiet_cmd__home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_java_unittest_target_copy_libjingle_peerconnection_java_unittest = ACTION _home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_java_unittest_target_copy_libjingle_peerconnection_java_unittest $@
cmd__home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_java_unittest_target_copy_libjingle_peerconnection_java_unittest = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd talk; mkdir -p $(builddir); bash -c "rm -f $(builddir)/libjingle_peerconnection_java_unittest && sed -e \"s@GYP_JAVA_HOME@/usr/lib/jvm/java-1.7.0-openjdk-i386@\" < app/webrtc/javatests/libjingle_peerconnection_java_unittest.sh > $(builddir)/libjingle_peerconnection_java_unittest && cp ../third_party/junit/junit-4.11.jar $(builddir) && chmod u+x $(builddir)/libjingle_peerconnection_java_unittest"

$(builddir)/libjingle_peerconnection_java_unittest: obj := $(abs_obj)
$(builddir)/libjingle_peerconnection_java_unittest: builddir := $(abs_builddir)
$(builddir)/libjingle_peerconnection_java_unittest: TOOLSET := $(TOOLSET)
$(builddir)/libjingle_peerconnection_java_unittest: talk/app/webrtc/javatests/libjingle_peerconnection_java_unittest.sh $(builddir)/libjingle_peerconnection_test_jar third_party/junit/junit-4.11.jar FORCE_DO_CMD
	$(call do_cmd,_home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_java_unittest_target_copy_libjingle_peerconnection_java_unittest)

all_deps += $(builddir)/libjingle_peerconnection_java_unittest
action__home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_java_unittest_target_copy_libjingle_peerconnection_java_unittest_outputs := $(builddir)/libjingle_peerconnection_java_unittest


### Rules for final target.
# Build our special outputs first.
$(obj).target/talk/libjingle_peerconnection_java_unittest.stamp: | $(action__home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_java_unittest_target_copy_libjingle_peerconnection_java_unittest_outputs)

# Preserve order dependency of special output on deps.
$(action__home_lht_webrtc_trunk_talk_libjingle_tests_gyp_libjingle_peerconnection_java_unittest_target_copy_libjingle_peerconnection_java_unittest_outputs): | $(obj).target/build/linux/ssl.stamp

$(obj).target/talk/libjingle_peerconnection_java_unittest.stamp: TOOLSET := $(TOOLSET)
$(obj).target/talk/libjingle_peerconnection_java_unittest.stamp: $(obj).target/build/linux/ssl.stamp FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/talk/libjingle_peerconnection_java_unittest.stamp
# Add target alias
.PHONY: libjingle_peerconnection_java_unittest
libjingle_peerconnection_java_unittest: $(obj).target/talk/libjingle_peerconnection_java_unittest.stamp

# Add target alias to "all" target.
.PHONY: all
all: libjingle_peerconnection_java_unittest

