# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := libjingle_unittest
DEFS_Debug := \
	'-DV8_DEPRECATION_WARNINGS' \
	'-DEXPAT_RELATIVE_PATH' \
	'-DFEATURE_ENABLE_VOICEMAIL' \
	'-DGTEST_RELATIVE_PATH' \
	'-DJSONCPP_RELATIVE_PATH' \
	'-DLOGGING=1' \
	'-DSRTP_RELATIVE_PATH' \
	'-DFEATURE_ENABLE_SSL' \
	'-DFEATURE_ENABLE_PSTN' \
	'-DHAVE_SRTP' \
	'-DHAVE_WEBRTC_VIDEO' \
	'-DHAVE_WEBRTC_VOICE' \
	'-DUSE_WEBRTC_DEV_BRANCH' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DTOOLKIT_VIEWS=1' \
	'-DUI_COMPOSITOR_IMAGE_TRANSPORT' \
	'-DUSE_AURA=1' \
	'-DUSE_CAIRO=1' \
	'-DUSE_GLIB=1' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DUSE_CLIPBOARD_AURAX11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DUSE_XI2_MT=2' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_CDMS' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DUSE_UDEV' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_AUTOFILL_DIALOG=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DCLD_VERSION=2' \
	'-DENABLE_FULL_PRINTING=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_SPELLCHECK=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_APP_LIST=1' \
	'-DENABLE_SETTINGS_APP=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DENABLE_MDNS=1' \
	'-DLIBPEERCONNECTION_LIB=1' \
	'-DLINUX' \
	'-DHAVE_SCTP' \
	'-DHASH_NAMESPACE=__gnu_cxx' \
	'-DPOSIX' \
	'-DDISABLE_DYNAMIC_CAST' \
	'-D_REENTRANT' \
	'-DSSL_USE_NSS' \
	'-DHAVE_NSS_SSL_H' \
	'-DSSL_USE_NSS_RNG' \
	'-D_VARIADIC_MAX=10' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-unused-local-typedefs \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-Wno-format \
	-Wno-unused-result \
	-m32 \
	-mmmx \
	-march=pentium4 \
	-msse2 \
	-mfpmath=sse \
	-O0 \
	-g \
	-funwind-tables

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated

INCS_Debug := \
	-I. \
	-Ithird_party \
	-Ithird_party/webrtc \
	-Iwebrtc \
	-Inet/third_party/nss/ssl \
	-Itesting/gtest/include \
	-Ithird_party/jsoncpp/overrides/include \
	-Ithird_party/jsoncpp/source/include \
	-Ithird_party/libyuv/include

DEFS_Release := \
	'-DV8_DEPRECATION_WARNINGS' \
	'-DEXPAT_RELATIVE_PATH' \
	'-DFEATURE_ENABLE_VOICEMAIL' \
	'-DGTEST_RELATIVE_PATH' \
	'-DJSONCPP_RELATIVE_PATH' \
	'-DLOGGING=1' \
	'-DSRTP_RELATIVE_PATH' \
	'-DFEATURE_ENABLE_SSL' \
	'-DFEATURE_ENABLE_PSTN' \
	'-DHAVE_SRTP' \
	'-DHAVE_WEBRTC_VIDEO' \
	'-DHAVE_WEBRTC_VOICE' \
	'-DUSE_WEBRTC_DEV_BRANCH' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DTOOLKIT_VIEWS=1' \
	'-DUI_COMPOSITOR_IMAGE_TRANSPORT' \
	'-DUSE_AURA=1' \
	'-DUSE_CAIRO=1' \
	'-DUSE_GLIB=1' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DUSE_CLIPBOARD_AURAX11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DUSE_XI2_MT=2' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_CDMS' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DUSE_UDEV' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_AUTOFILL_DIALOG=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DCLD_VERSION=2' \
	'-DENABLE_FULL_PRINTING=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_SPELLCHECK=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_APP_LIST=1' \
	'-DENABLE_SETTINGS_APP=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DENABLE_MDNS=1' \
	'-DLIBPEERCONNECTION_LIB=1' \
	'-DLINUX' \
	'-DHAVE_SCTP' \
	'-DHASH_NAMESPACE=__gnu_cxx' \
	'-DPOSIX' \
	'-DDISABLE_DYNAMIC_CAST' \
	'-D_REENTRANT' \
	'-DSSL_USE_NSS' \
	'-DHAVE_NSS_SSL_H' \
	'-DSSL_USE_NSS_RNG' \
	'-D_VARIADIC_MAX=10' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-unused-local-typedefs \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-Wno-format \
	-Wno-unused-result \
	-m32 \
	-mmmx \
	-march=pentium4 \
	-msse2 \
	-mfpmath=sse \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections \
	-funwind-tables

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated

INCS_Release := \
	-I. \
	-Ithird_party \
	-Ithird_party/webrtc \
	-Iwebrtc \
	-Inet/third_party/nss/ssl \
	-Itesting/gtest/include \
	-Ithird_party/jsoncpp/overrides/include \
	-Ithird_party/jsoncpp/source/include \
	-Ithird_party/libyuv/include

OBJS := \
	$(obj).target/$(TARGET)/talk/base/asynchttprequest_unittest.o \
	$(obj).target/$(TARGET)/talk/base/atomicops_unittest.o \
	$(obj).target/$(TARGET)/talk/base/autodetectproxy_unittest.o \
	$(obj).target/$(TARGET)/talk/base/bandwidthsmoother_unittest.o \
	$(obj).target/$(TARGET)/talk/base/base64_unittest.o \
	$(obj).target/$(TARGET)/talk/base/basictypes_unittest.o \
	$(obj).target/$(TARGET)/talk/base/bind_unittest.o \
	$(obj).target/$(TARGET)/talk/base/buffer_unittest.o \
	$(obj).target/$(TARGET)/talk/base/bytebuffer_unittest.o \
	$(obj).target/$(TARGET)/talk/base/byteorder_unittest.o \
	$(obj).target/$(TARGET)/talk/base/callback_unittest.o \
	$(obj).target/$(TARGET)/talk/base/cpumonitor_unittest.o \
	$(obj).target/$(TARGET)/talk/base/crc32_unittest.o \
	$(obj).target/$(TARGET)/talk/base/event_unittest.o \
	$(obj).target/$(TARGET)/talk/base/filelock_unittest.o \
	$(obj).target/$(TARGET)/talk/base/fileutils_unittest.o \
	$(obj).target/$(TARGET)/talk/base/helpers_unittest.o \
	$(obj).target/$(TARGET)/talk/base/httpbase_unittest.o \
	$(obj).target/$(TARGET)/talk/base/httpcommon_unittest.o \
	$(obj).target/$(TARGET)/talk/base/httpserver_unittest.o \
	$(obj).target/$(TARGET)/talk/base/ipaddress_unittest.o \
	$(obj).target/$(TARGET)/talk/base/logging_unittest.o \
	$(obj).target/$(TARGET)/talk/base/md5digest_unittest.o \
	$(obj).target/$(TARGET)/talk/base/messagedigest_unittest.o \
	$(obj).target/$(TARGET)/talk/base/messagequeue_unittest.o \
	$(obj).target/$(TARGET)/talk/base/multipart_unittest.o \
	$(obj).target/$(TARGET)/talk/base/nat_unittest.o \
	$(obj).target/$(TARGET)/talk/base/network_unittest.o \
	$(obj).target/$(TARGET)/talk/base/nullsocketserver_unittest.o \
	$(obj).target/$(TARGET)/talk/base/optionsfile_unittest.o \
	$(obj).target/$(TARGET)/talk/base/pathutils_unittest.o \
	$(obj).target/$(TARGET)/talk/base/physicalsocketserver_unittest.o \
	$(obj).target/$(TARGET)/talk/base/profiler_unittest.o \
	$(obj).target/$(TARGET)/talk/base/proxy_unittest.o \
	$(obj).target/$(TARGET)/talk/base/proxydetect_unittest.o \
	$(obj).target/$(TARGET)/talk/base/ratelimiter_unittest.o \
	$(obj).target/$(TARGET)/talk/base/ratetracker_unittest.o \
	$(obj).target/$(TARGET)/talk/base/referencecountedsingletonfactory_unittest.o \
	$(obj).target/$(TARGET)/talk/base/rollingaccumulator_unittest.o \
	$(obj).target/$(TARGET)/talk/base/scopedptrcollection_unittest.o \
	$(obj).target/$(TARGET)/talk/base/sha1digest_unittest.o \
	$(obj).target/$(TARGET)/talk/base/sharedexclusivelock_unittest.o \
	$(obj).target/$(TARGET)/talk/base/signalthread_unittest.o \
	$(obj).target/$(TARGET)/talk/base/sigslot_unittest.o \
	$(obj).target/$(TARGET)/talk/base/socket_unittest.o \
	$(obj).target/$(TARGET)/talk/base/socketaddress_unittest.o \
	$(obj).target/$(TARGET)/talk/base/stream_unittest.o \
	$(obj).target/$(TARGET)/talk/base/stringencode_unittest.o \
	$(obj).target/$(TARGET)/talk/base/stringutils_unittest.o \
	$(obj).target/$(TARGET)/talk/base/task_unittest.o \
	$(obj).target/$(TARGET)/talk/base/testclient_unittest.o \
	$(obj).target/$(TARGET)/talk/base/thread_unittest.o \
	$(obj).target/$(TARGET)/talk/base/timeutils_unittest.o \
	$(obj).target/$(TARGET)/talk/base/urlencode_unittest.o \
	$(obj).target/$(TARGET)/talk/base/versionparsing_unittest.o \
	$(obj).target/$(TARGET)/talk/base/virtualsocket_unittest.o \
	$(obj).target/$(TARGET)/talk/xmllite/qname_unittest.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlbuilder_unittest.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlelement_unittest.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlnsstack_unittest.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlparser_unittest.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlprinter_unittest.o \
	$(obj).target/$(TARGET)/talk/xmpp/hangoutpubsubclient_unittest.o \
	$(obj).target/$(TARGET)/talk/xmpp/jid_unittest.o \
	$(obj).target/$(TARGET)/talk/xmpp/mucroomconfigtask_unittest.o \
	$(obj).target/$(TARGET)/talk/xmpp/mucroomdiscoverytask_unittest.o \
	$(obj).target/$(TARGET)/talk/xmpp/mucroomlookuptask_unittest.o \
	$(obj).target/$(TARGET)/talk/xmpp/mucroomuniquehangoutidtask_unittest.o \
	$(obj).target/$(TARGET)/talk/xmpp/pingtask_unittest.o \
	$(obj).target/$(TARGET)/talk/xmpp/pubsubclient_unittest.o \
	$(obj).target/$(TARGET)/talk/xmpp/pubsubtasks_unittest.o \
	$(obj).target/$(TARGET)/talk/xmpp/util_unittest.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppengine_unittest.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmpplogintask_unittest.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppstanzaparser_unittest.o \
	$(obj).target/$(TARGET)/talk/base/latebindingsymboltable_unittest.o \
	$(obj).target/$(TARGET)/talk/base/linuxfdwalk_unittest.o \
	$(obj).target/$(TARGET)/talk/base/sslidentity_unittest.o \
	$(obj).target/$(TARGET)/talk/base/sslstreamadapter_unittest.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/build/linux/ssl.stamp $(obj).target/talk/libgunit.a $(obj).target/talk/libjingle.a $(obj).target/talk/libjingle_unittest_main.a $(obj).target/net/third_party/nss/libcrssl.a $(obj).target/third_party/expat/expat.stamp $(obj).target/third_party/jsoncpp/libjsoncpp.a $(builddir)/libyuv.a $(obj).target/third_party/libjpeg_turbo/libjpeg_turbo.a $(obj).target/third_party/libyuv/libyuv.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-m32 \
	-Wl,--no-as-needed

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-m32 \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	 \
	-lnss3 \
	-lnssutil3 \
	-lsmime3 \
	-lplds4 \
	-lplc4 \
	-lnspr4 \
	-ldl \
	-lcrypto \
	-lrt \
	-lXext \
	-lX11 \
	-lXcomposite \
	-lXrender \
	-lexpat

$(builddir)/libjingle_unittest: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/libjingle_unittest: LIBS := $(LIBS)
$(builddir)/libjingle_unittest: LD_INPUTS := $(OBJS) $(obj).target/talk/libgunit.a $(obj).target/talk/libjingle.a $(obj).target/talk/libjingle_unittest_main.a $(obj).target/net/third_party/nss/libcrssl.a $(obj).target/third_party/jsoncpp/libjsoncpp.a $(obj).target/third_party/libyuv/libyuv.a $(obj).target/third_party/libjpeg_turbo/libjpeg_turbo.a
$(builddir)/libjingle_unittest: TOOLSET := $(TOOLSET)
$(builddir)/libjingle_unittest: $(OBJS) $(obj).target/talk/libgunit.a $(obj).target/talk/libjingle.a $(obj).target/talk/libjingle_unittest_main.a $(obj).target/net/third_party/nss/libcrssl.a $(obj).target/third_party/jsoncpp/libjsoncpp.a $(obj).target/third_party/libyuv/libyuv.a $(obj).target/third_party/libjpeg_turbo/libjpeg_turbo.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/libjingle_unittest
# Add target alias
.PHONY: libjingle_unittest
libjingle_unittest: $(builddir)/libjingle_unittest

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/libjingle_unittest

