


OBJECTS_DIR = ../tmp/$$TARGET


INCLUDEPATH     += ..

DEFINES += JSONCPP_RELATIVE_PATH LOGGING=1  \
    LIBPEERCONNECTION_LIB=1  USE_WEBRTC_DEV_BRANCH \

#',
#'    HAVE_WEBRTC_VIDEO HAVE_WEBRTC_VOICE \
#SRTP_RELATIVE_PATH HAVE_SRTP


win32 {

Debug:DEFINES +=_DEBUG
Release:DEFINES +=
DEFINES += _UNICODE UNICODE WIN32_LEAN_AND_MEAN

} else:macx {
} else {
    DEFINES += POSIX LINUX
}

#unix {
#    target.path = /usr/lib
#    INSTALLS += target
#}
