# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := libjingle
DEFS_Debug := \
	'-DV8_DEPRECATION_WARNINGS' \
	'-DEXPAT_RELATIVE_PATH' \
	'-DFEATURE_ENABLE_VOICEMAIL' \
	'-DGTEST_RELATIVE_PATH' \
	'-DJSONCPP_RELATIVE_PATH' \
	'-DLOGGING=1' \
	'-DSRTP_RELATIVE_PATH' \
	'-DFEATURE_ENABLE_SSL' \
	'-DFEATURE_ENABLE_PSTN' \
	'-DHAVE_SRTP' \
	'-DHAVE_WEBRTC_VIDEO' \
	'-DHAVE_WEBRTC_VOICE' \
	'-DUSE_WEBRTC_DEV_BRANCH' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DTOOLKIT_VIEWS=1' \
	'-DUI_COMPOSITOR_IMAGE_TRANSPORT' \
	'-DUSE_AURA=1' \
	'-DUSE_CAIRO=1' \
	'-DUSE_GLIB=1' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DUSE_CLIPBOARD_AURAX11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DUSE_XI2_MT=2' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_CDMS' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DUSE_UDEV' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_AUTOFILL_DIALOG=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DCLD_VERSION=2' \
	'-DENABLE_FULL_PRINTING=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_SPELLCHECK=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_APP_LIST=1' \
	'-DENABLE_SETTINGS_APP=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DENABLE_MDNS=1' \
	'-DLIBPEERCONNECTION_LIB=1' \
	'-DLINUX' \
	'-DHAVE_SCTP' \
	'-DHASH_NAMESPACE=__gnu_cxx' \
	'-DPOSIX' \
	'-DDISABLE_DYNAMIC_CAST' \
	'-D_REENTRANT' \
	'-DSSL_USE_NSS' \
	'-DHAVE_NSS_SSL_H' \
	'-DSSL_USE_NSS_RNG' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-unused-local-typedefs \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-Wno-format \
	-Wno-unused-result \
	-m32 \
	-mmmx \
	-march=pentium4 \
	-msse2 \
	-mfpmath=sse \
	-O0 \
	-g \
	-funwind-tables

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated

INCS_Debug := \
	-I. \
	-Ithird_party \
	-Ithird_party/webrtc \
	-Iwebrtc \
	-Inet/third_party/nss/ssl \
	-Ithird_party/jsoncpp/overrides/include \
	-Ithird_party/jsoncpp/source/include

DEFS_Release := \
	'-DV8_DEPRECATION_WARNINGS' \
	'-DEXPAT_RELATIVE_PATH' \
	'-DFEATURE_ENABLE_VOICEMAIL' \
	'-DGTEST_RELATIVE_PATH' \
	'-DJSONCPP_RELATIVE_PATH' \
	'-DLOGGING=1' \
	'-DSRTP_RELATIVE_PATH' \
	'-DFEATURE_ENABLE_SSL' \
	'-DFEATURE_ENABLE_PSTN' \
	'-DHAVE_SRTP' \
	'-DHAVE_WEBRTC_VIDEO' \
	'-DHAVE_WEBRTC_VOICE' \
	'-DUSE_WEBRTC_DEV_BRANCH' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DCHROMIUM_BUILD' \
	'-DTOOLKIT_VIEWS=1' \
	'-DUI_COMPOSITOR_IMAGE_TRANSPORT' \
	'-DUSE_AURA=1' \
	'-DUSE_CAIRO=1' \
	'-DUSE_GLIB=1' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DUSE_CLIPBOARD_AURAX11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DUSE_XI2_MT=2' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_CDMS' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DUSE_UDEV' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_AUTOFILL_DIALOG=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DCLD_VERSION=2' \
	'-DENABLE_FULL_PRINTING=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_SPELLCHECK=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_APP_LIST=1' \
	'-DENABLE_SETTINGS_APP=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DENABLE_MDNS=1' \
	'-DLIBPEERCONNECTION_LIB=1' \
	'-DLINUX' \
	'-DHAVE_SCTP' \
	'-DHASH_NAMESPACE=__gnu_cxx' \
	'-DPOSIX' \
	'-DDISABLE_DYNAMIC_CAST' \
	'-D_REENTRANT' \
	'-DSSL_USE_NSS' \
	'-DHAVE_NSS_SSL_H' \
	'-DSSL_USE_NSS_RNG' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-unused-local-typedefs \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-Wno-format \
	-Wno-unused-result \
	-m32 \
	-mmmx \
	-march=pentium4 \
	-msse2 \
	-mfpmath=sse \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections \
	-funwind-tables

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated

INCS_Release := \
	-I. \
	-Ithird_party \
	-Ithird_party/webrtc \
	-Iwebrtc \
	-Inet/third_party/nss/ssl \
	-Ithird_party/jsoncpp/overrides/include \
	-Ithird_party/jsoncpp/source/include

OBJS := \
	$(obj).target/$(TARGET)/talk/base/asyncfile.o \
	$(obj).target/$(TARGET)/talk/base/asynchttprequest.o \
	$(obj).target/$(TARGET)/talk/base/asyncinvoker.o \
	$(obj).target/$(TARGET)/talk/base/asyncsocket.o \
	$(obj).target/$(TARGET)/talk/base/asynctcpsocket.o \
	$(obj).target/$(TARGET)/talk/base/asyncudpsocket.o \
	$(obj).target/$(TARGET)/talk/base/autodetectproxy.o \
	$(obj).target/$(TARGET)/talk/base/bandwidthsmoother.o \
	$(obj).target/$(TARGET)/talk/base/base64.o \
	$(obj).target/$(TARGET)/talk/base/bytebuffer.o \
	$(obj).target/$(TARGET)/talk/base/checks.o \
	$(obj).target/$(TARGET)/talk/base/common.o \
	$(obj).target/$(TARGET)/talk/base/cpumonitor.o \
	$(obj).target/$(TARGET)/talk/base/crc32.o \
	$(obj).target/$(TARGET)/talk/base/diskcache.o \
	$(obj).target/$(TARGET)/talk/base/event.o \
	$(obj).target/$(TARGET)/talk/base/filelock.o \
	$(obj).target/$(TARGET)/talk/base/fileutils.o \
	$(obj).target/$(TARGET)/talk/base/firewallsocketserver.o \
	$(obj).target/$(TARGET)/talk/base/flags.o \
	$(obj).target/$(TARGET)/talk/base/helpers.o \
	$(obj).target/$(TARGET)/talk/base/httpbase.o \
	$(obj).target/$(TARGET)/talk/base/httpclient.o \
	$(obj).target/$(TARGET)/talk/base/httpcommon.o \
	$(obj).target/$(TARGET)/talk/base/httprequest.o \
	$(obj).target/$(TARGET)/talk/base/httpserver.o \
	$(obj).target/$(TARGET)/talk/base/ifaddrs-android.o \
	$(obj).target/$(TARGET)/talk/base/ipaddress.o \
	$(obj).target/$(TARGET)/talk/base/json.o \
	$(obj).target/$(TARGET)/talk/base/logging.o \
	$(obj).target/$(TARGET)/talk/base/md5.o \
	$(obj).target/$(TARGET)/talk/base/messagedigest.o \
	$(obj).target/$(TARGET)/talk/base/messagehandler.o \
	$(obj).target/$(TARGET)/talk/base/messagequeue.o \
	$(obj).target/$(TARGET)/talk/base/multipart.o \
	$(obj).target/$(TARGET)/talk/base/natserver.o \
	$(obj).target/$(TARGET)/talk/base/natsocketfactory.o \
	$(obj).target/$(TARGET)/talk/base/nattypes.o \
	$(obj).target/$(TARGET)/talk/base/nethelpers.o \
	$(obj).target/$(TARGET)/talk/base/network.o \
	$(obj).target/$(TARGET)/talk/base/nssidentity.o \
	$(obj).target/$(TARGET)/talk/base/nssstreamadapter.o \
	$(obj).target/$(TARGET)/talk/base/optionsfile.o \
	$(obj).target/$(TARGET)/talk/base/pathutils.o \
	$(obj).target/$(TARGET)/talk/base/physicalsocketserver.o \
	$(obj).target/$(TARGET)/talk/base/profiler.o \
	$(obj).target/$(TARGET)/talk/base/proxydetect.o \
	$(obj).target/$(TARGET)/talk/base/proxyinfo.o \
	$(obj).target/$(TARGET)/talk/base/proxyserver.o \
	$(obj).target/$(TARGET)/talk/base/ratelimiter.o \
	$(obj).target/$(TARGET)/talk/base/ratetracker.o \
	$(obj).target/$(TARGET)/talk/base/sha1.o \
	$(obj).target/$(TARGET)/talk/base/sharedexclusivelock.o \
	$(obj).target/$(TARGET)/talk/base/signalthread.o \
	$(obj).target/$(TARGET)/talk/base/socketadapters.o \
	$(obj).target/$(TARGET)/talk/base/socketaddress.o \
	$(obj).target/$(TARGET)/talk/base/socketaddresspair.o \
	$(obj).target/$(TARGET)/talk/base/socketpool.o \
	$(obj).target/$(TARGET)/talk/base/socketstream.o \
	$(obj).target/$(TARGET)/talk/base/ssladapter.o \
	$(obj).target/$(TARGET)/talk/base/sslfingerprint.o \
	$(obj).target/$(TARGET)/talk/base/sslidentity.o \
	$(obj).target/$(TARGET)/talk/base/sslsocketfactory.o \
	$(obj).target/$(TARGET)/talk/base/sslstreamadapter.o \
	$(obj).target/$(TARGET)/talk/base/sslstreamadapterhelper.o \
	$(obj).target/$(TARGET)/talk/base/stream.o \
	$(obj).target/$(TARGET)/talk/base/stringencode.o \
	$(obj).target/$(TARGET)/talk/base/stringutils.o \
	$(obj).target/$(TARGET)/talk/base/systeminfo.o \
	$(obj).target/$(TARGET)/talk/base/task.o \
	$(obj).target/$(TARGET)/talk/base/taskparent.o \
	$(obj).target/$(TARGET)/talk/base/taskrunner.o \
	$(obj).target/$(TARGET)/talk/base/testclient.o \
	$(obj).target/$(TARGET)/talk/base/thread.o \
	$(obj).target/$(TARGET)/talk/base/timeutils.o \
	$(obj).target/$(TARGET)/talk/base/timing.o \
	$(obj).target/$(TARGET)/talk/base/transformadapter.o \
	$(obj).target/$(TARGET)/talk/base/urlencode.o \
	$(obj).target/$(TARGET)/talk/base/versionparsing.o \
	$(obj).target/$(TARGET)/talk/base/virtualsocketserver.o \
	$(obj).target/$(TARGET)/talk/base/worker.o \
	$(obj).target/$(TARGET)/talk/xmllite/qname.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlbuilder.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlconstants.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlelement.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlnsstack.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlparser.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlprinter.o \
	$(obj).target/$(TARGET)/talk/xmpp/chatroommoduleimpl.o \
	$(obj).target/$(TARGET)/talk/xmpp/constants.o \
	$(obj).target/$(TARGET)/talk/xmpp/discoitemsquerytask.o \
	$(obj).target/$(TARGET)/talk/xmpp/hangoutpubsubclient.o \
	$(obj).target/$(TARGET)/talk/xmpp/iqtask.o \
	$(obj).target/$(TARGET)/talk/xmpp/jid.o \
	$(obj).target/$(TARGET)/talk/xmpp/moduleimpl.o \
	$(obj).target/$(TARGET)/talk/xmpp/mucroomconfigtask.o \
	$(obj).target/$(TARGET)/talk/xmpp/mucroomdiscoverytask.o \
	$(obj).target/$(TARGET)/talk/xmpp/mucroomlookuptask.o \
	$(obj).target/$(TARGET)/talk/xmpp/mucroomuniquehangoutidtask.o \
	$(obj).target/$(TARGET)/talk/xmpp/pingtask.o \
	$(obj).target/$(TARGET)/talk/xmpp/presenceouttask.o \
	$(obj).target/$(TARGET)/talk/xmpp/presencereceivetask.o \
	$(obj).target/$(TARGET)/talk/xmpp/presencestatus.o \
	$(obj).target/$(TARGET)/talk/xmpp/pubsub_task.o \
	$(obj).target/$(TARGET)/talk/xmpp/pubsubclient.o \
	$(obj).target/$(TARGET)/talk/xmpp/pubsubstateclient.o \
	$(obj).target/$(TARGET)/talk/xmpp/pubsubtasks.o \
	$(obj).target/$(TARGET)/talk/xmpp/receivetask.o \
	$(obj).target/$(TARGET)/talk/xmpp/rostermoduleimpl.o \
	$(obj).target/$(TARGET)/talk/xmpp/saslmechanism.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppauth.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppclient.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppengineimpl.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppengineimpl_iq.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmpplogintask.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmpppump.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppsocket.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppstanzaparser.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmpptask.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppthread.o \
	$(obj).target/$(TARGET)/talk/base/linux.o \
	$(obj).target/$(TARGET)/talk/base/dbus.o \
	$(obj).target/$(TARGET)/talk/base/libdbusglibsymboltable.o \
	$(obj).target/$(TARGET)/talk/base/linuxfdwalk.o \
	$(obj).target/$(TARGET)/talk/base/linuxwindowpicker.o \
	$(obj).target/$(TARGET)/talk/base/latebindingsymboltable.o \
	$(obj).target/$(TARGET)/talk/base/posix.o \
	$(obj).target/$(TARGET)/talk/base/unixfilesystem.o \
	$(obj).target/$(TARGET)/talk/base/openssladapter.o \
	$(obj).target/$(TARGET)/talk/base/openssldigest.o \
	$(obj).target/$(TARGET)/talk/base/opensslidentity.o \
	$(obj).target/$(TARGET)/talk/base/opensslstreamadapter.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/build/linux/ssl.stamp $(obj).target/third_party/expat/expat.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-m32 \
	-Wl,--no-as-needed

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-m32 \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	

$(obj).target/talk/libjingle.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/talk/libjingle.a: LIBS := $(LIBS)
$(obj).target/talk/libjingle.a: TOOLSET := $(TOOLSET)
$(obj).target/talk/libjingle.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/talk/libjingle.a
# Add target alias
.PHONY: libjingle
libjingle: $(obj).target/talk/libjingle.a

# Add target alias to "all" target.
.PHONY: all
all: libjingle

